### ISSUE TITLE
签到时提示升级会员

### ISSUE THREAD

**Issue by yaoysyao** [tyIceStream/GLaDOS_Checkin#19]
签到时提示这个，有知道的兄弟怎么破吗，是必须要开会员，不能白嫖了吗
![image](https://user-images.githubusercontent.com/38513384/177812505-a42b6fe2-a718-40e5-a8ea-3f12686feb93.png)

**Comment by tyIceStream** [comment]
不太清楚哎，要不你去telegram的群一下。或者你注册若干个小号一直白嫖？

**Comment by zhangyuxiang27** [comment]
还是限制了我的想象 只有我一个人买了吗

**Comment by yaoysyao** [comment]
问了客服，好像试用用户不允许签到白嫖了，只能购买了会员才可以进行签到
