### ISSUE TITLE
大佬可否有时间考虑增加server酱之类的消息通知功能

### ISSUE THREAD

**Issue by jiarui666** [tyIceStream/GLaDOS_Checkin#2]

**Comment by jiarui666** [comment]
十分感谢，cookie失效会导致workflow失败吗（失败后github会给发送邮件通知也是极好的）。我前两次的workflow好像cookie问题报错了
![image](https://user-images.githubusercontent.com/45376160/176405993-ee97bddb-a810-4bd2-ba3f-2725983ffb48.png)

**Comment by tyIceStream** [comment]
对Cookie检验的功能也会在近期更新的

**Comment by tyIceStream** [comment]
消息通知功能已部署
