### ISSUE TITLE
可以在Linux上使用吗

### ISSUE THREAD

**Issue by FlyfishO25** [tyIceStream/GLaDOS_Checkin#20]
脚本可否在Linux上使用？

**Comment by seggp** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tyIceStream** [comment]
应该是可以的，没有界面的话需要开headless。选择用Windows的系统是因为图形界面在反爬虫中确有优势。
