### ISSUE TITLE
自动同步代码时想要忽略掉仓库中的某些文件

### ISSUE THREAD

**Issue by yaoysyao** [tyIceStream/GLaDOS_Checkin#22]
在自动同步代码时，我想要忽略掉某些文件的自动同步，看了下github-sync 的代码，好像不能忽略，有啥方法吗

**Comment by seggp** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yaoysyao** [comment]
> 暂时没有比较好的方法，可以自己重写一个Action来实现这个功能。

OKOK
