### ISSUE TITLE
你好，我的cookies出问题了，无法签到，可以帮忙看一下吗？

### ISSUE THREAD

**Issue by APHEFSDS** [tyIceStream/GLaDOS_Checkin#23]
Run python3 ./glados/main.py --cookie_string ""
usage: main.py [-h] --cookie_string COOKIE_STRING
main.py: error: argument --cookie_string: expected one argument
Error: Process completed with exit code 1.

**Comment by tyIceStream** [comment]
@APHEFSDS 你的报错的原因是没有收到Cookie。你可以确认一下你的Cookie的名字是不是【GLADOS_COOKIE】，大小写敏感，不能多字母也不能少字母。

**Comment by APHEFSDS** [comment]
非常感谢回复。我发现了我一个致命的错误。作为无编程基础的门外汉，我没有严谨的按照操作指南来操作，错误的把cookie创建在了dependabot而不是action。两者操作类似。果然是莫名其妙的bug总是在奇葩的操作后面。

**Comment by seggp** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
