### ISSUE TITLE
Actions报错了

### ISSUE THREAD

**Issue by wudongdefeng** [tyIceStream/GLaDOS_Checkin#25]
大佬看看Actions报错了

**Comment by seggp** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tyIceStream** [comment]
是由于上游依赖更新导致的问题，undetected-chromedriver昨天的版本是3.1.7，今天自动更新成3.2.0了。

**Comment by tyIceStream** [comment]
这个问题可以通过强制将版本指定为3.1.7来解决。我已经Report给undetected-chromedriver的owner了，暂时先看一下他那边提出的方案吧。

**Comment by tyIceStream** [comment]
更新了一下Python版本，问题已解决。与本仓库保持一致即可。

**Comment by wudongdefeng** [comment]
可以了
