### ISSUE TITLE
返回的message信息太少

### ISSUE THREAD

**Issue by AstbReal** [tyIceStream/GLaDOS_Checkin#3]
大佬，能不能从`https://glados.rocks/api/user/status`中获取更多信息，比如使用量`traffic`等？

**Comment by tyIceStream** [comment]
最新实现中`glados_status`中给出了向`https://glados.rocks/api/user/status`查询的方案，虽然其中含有traffic信息，但是并没有总量，我看你的代码好像写死了200G，似乎也不是很方便。

**Comment by AstbReal** [comment]
200G似乎与status['vip']有关系,1是10G，11是50G,21是200G。当然这是我猜测的。
