### ISSUE TITLE
增加日志功能和多账号登录

### ISSUE THREAD

**Issue by yaoysyao** [tyIceStream/GLaDOS_Checkin#7]
是否考虑增加日志功能，因为我发现我fork了代码，配置了cookie，action也启动了，但是好像没有执行签到，也不知道是哪里的问题，
是否考虑增加多账号登录
是否考虑增加推送至微信比如server酱

**Comment by tyIceStream** [comment]
我看了你的Actions，是执行签到的。此外你可以和本仓库同步一下，新的commit中完善了一些日志的功能。
多账号和推送会考虑。

**Comment by yaoysyao** [comment]
> 我看了你的Actions，是执行签到的。此外你可以和本仓库同步一下，新的commit中完善了一些日志的功能。 多账号和推送会考虑。

好的，刚才我自己增加了一下多账号登录，改了下日志记录，因为不太懂调用谷歌浏览器那块的代码，就直接用的循环，效率可能不高，我自己先凑合用，坐等你更新了

**Comment by tyIceStream** [comment]
非常感谢，多账号的功能将在近期发布

**Comment by tyIceStream** [comment]
多账号打卡功能已经部署

**Comment by tyIceStream** [comment]
你认为还需要增加什么日志？我认为签到时间不是很重要，Actions本身是可以显示时间戳的

**Comment by yaoysyao** [comment]
> 你认为还需要增加什么日志？我认为签到时间不是很重要，Actions本身是可以显示时间戳的

如果可以显示就不用加了，我主要是想看到签到的时间和我设置的时间是不是一样的，顺便看一下每天有没有成功，如果本身就可以看到，那就不需要加了

**Comment by tyIceStream** [comment]
Actions里面时间都是UTC+0的时间，跟中国差8个小时的
